services:
  db:
    image: postgres:14
    #container_name: medicomtel_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: base_test
    profiles: ["core"]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -h localhost"]
      interval: 3s
      timeout: 2s
      retries: 20

  simulator:  
    build: ./simulator
    container_name: medicomtel_simulator
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    profiles: ["workers"]
    networks:
      - backend
    environment:
    - API_BASE=http://api:8000    # ⬅️ remplace API_URL

  api:  
    build: ./api
    #container_name: medicomtel_apiv1 (on gère le nom dynamiquement)
    profiles: ["core"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health | grep -q '\"status\":\"up\"'"]
      interval: 3s
      timeout: 2s
      retries: 40
    
  grafana: 
    image: grafana/grafana:latest
    container_name: medicomtel_dashboard
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - db
    ports:
      - "8082:3000" 
    networks:
      - frontend
      - backend
    profiles: ["viz"]
    volumes:
    - grafana_data:/var/lib/grafana
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

  analyzer:
    build: ./analyzer
    container_name: medicomtel_analyzer
    restart : unless-stopped
    depends_on:
      api:
          condition: service_started
    networks:
      - backend
    profiles: ["workers"]     
    environment:
      - API_URL=http://api:8000/alertes
      - LOOKBACK_SECONDS=15
      - SLEEP_SECONDS=2

  cli:
    build: ./UserInterface          # dossier où se trouve Dockerfile + CLI.py + requirements.txt
    container_name: medicomtel_cli
    profiles: ["cli"]
    networks:
      - backend            # même réseau que l'API
    stdin_open: true       # pour input()
    tty: true              # pour un TTY interactif
    environment:
      - API_URL=http://api:8000   # inside Docker, utilise le nom de service

  nginx:
    image: nginx:alpine
    container_name: medicomtel_nginx
    profiles: ["lb"]  
    depends_on:
      api:
        condition: service_started
    ports:
      - "8081:80"   # on accède à http://localhost:8081
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend

volumes:
  db_data:
  grafana_data:

networks:
  frontend:
  backend: