{
 "title": "Vue Docteur",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Alertes ! ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "base_test",
     "rawSql": "SELECT\n  a.ts AS \"time\",\n  p.nom || ' ' || p.prenom AS \"Patient\",\n  a.type AS \"Type d’alerte\",\n  a.severity AS \"Gravité\",\n  a.message AS \"Message\"\nFROM alertes a\nJOIN patients p ON a.patient_id = p.id\nWHERE $__timeFilter(a.ts)\nORDER BY a.ts DESC;\n"
    }
   ]
  },
  {
   "title": "Suivi BPM par patient",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "base_test",
     "rawSql": "SELECT\n  t.ts AS \"time\",\n  t.hr AS \"value\",\n  ('Patient ' || t.patient_id::text) AS \"metric\"\nFROM telemetrie t\nWHERE t.hr IS NOT NULL\n  AND t.hr BETWEEN 40 AND 190\n  AND t.ts > NOW() - INTERVAL '5 minutes'\nORDER BY t.ts ASC;\n"
    }
   ]
  },
  {
   "title": "Dossiers en attente",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "base_test",
     "rawSql": "SELECT nom, prenom, type_patient\nFROM patients\nWHERE statut = 'cli';\n"
    }
   ]
  }
 ]
}